### PR TITLE
PLAT-1418 : opentdf example using client-web

### PR DESCRIPTION
**Pull request by obidenko**
Signed-off-by: obidenko <obidenko@virtru.com>

### CODE REVIEW

**Comment by dmihalcik-virtru** [comment]
@obidenko I've refreshed it to the latest settings. I'm having trouble getting it to load in tilt - I'm guessing webpack's dev server isn't configured properly with the k8s configuration (and maybe something is wrong with my keycloak config, too)

**Comment by dmihalcik-virtru** [comment]
Ideally we'd add a playwright test at the end that runs against the tilt'ed configuration

**Comment by obidenko** [comment]
> @obidenko I've refreshed it to the latest settings. I'm having trouble getting it to load in tilt - I'm guessing webpack's dev server isn't configured properly with the k8s configuration (and maybe something is wrong with my keycloak config, too)

I'll check it after abacship demo

**Comment by cassandrabailey293** [comment]
closing in favor of https://github.com/opentdf/opentdf/tree/main/examples/webcam-app , which is an example nano tdf client app.

**Pull request closed without merging**
